# File: .github/workflows/setup-node/action.yml
name: setup-node
description: 'Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js ⚙️
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: 🤌 Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Cache dependencies ⚡
      id: cache_dependencies
      uses: actions/cache@v3
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies 🔧
      shell: bash
      if: steps.cache_dependencies.outputs.cache-hit != 'true'
      run: pnpm install --fix-lockfile --config.auto-install-peers=false
      # run: npm ci --legacy-peer-deps
